import type { Metadata } from "next";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Terms of Use — HealthShare",
  description:
    "HealthShare Terms of Use, including subscription, billing, and acceptable use terms.",
};

const EFFECTIVE_DATE = "June 28, 2026";

export default function TermsPage() {
  return (
    <>
      <Nav />
      <main className="pt-32 pb-24 px-6 bg-white dark:bg-gray-950">
        <article className="max-w-3xl mx-auto text-gray-700 dark:text-gray-300 leading-relaxed">
          <h1 className="text-4xl sm:text-5xl font-bold text-gray-900 dark:text-white tracking-tight mb-3">
            Terms of Use
          </h1>
          <p className="text-sm text-gray-500 dark:text-gray-400 mb-12">
            Effective {EFFECTIVE_DATE}
          </p>

          <Section title="1. Acceptance">
            <p>
              These Terms of Use (the &ldquo;Terms&rdquo;) govern your use of the HealthShare
              mobile application and related services (collectively, the &ldquo;App&rdquo;).
              By downloading, installing, or using the App, you agree to these Terms. If you
              do not agree, do not use the App.
            </p>
          </Section>

          <Section title="2. License">
            <p>
              Subject to your compliance with these Terms, you are granted a personal,
              limited, non-exclusive, non-transferable, revocable license to install and use
              the App on any Apple-branded device you own or control, in accordance with the
              Apple Media Services Terms and the standard Apple End User License Agreement
              (the &ldquo;EULA&rdquo;) available at{" "}
              <a
                href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/"
                target="_blank"
                rel="noopener noreferrer"
                className="text-[#00B5A3] hover:underline"
              >
                apple.com/legal/internet-services/itunes/dev/stdeula
              </a>
              . These Terms are entered into between you and HealthShare; Apple is not a
              party.
            </p>
          </Section>

          <Section title="3. Subscriptions and Billing">
            <p>
              Certain features of the App require a paid subscription (&ldquo;HealthShare
              Pro&rdquo;). Subscriptions are sold as auto-renewable in-app purchases through
              your Apple ID.
            </p>
            <ul className="list-disc pl-6 mt-4 space-y-2">
              <li>
                Payment is charged to your Apple ID at confirmation of purchase.
              </li>
              <li>
                Your subscription renews automatically at the end of each billing period
                unless auto-renewal is turned off at least 24 hours before the end of the
                current period.
              </li>
              <li>
                The renewal charge is applied to your Apple ID within 24 hours prior to the
                end of the current period, at the then-current subscription price.
              </li>
              <li>
                You can manage or cancel your subscription at any time in your Apple ID
                account settings under <em>Subscriptions</em>. Canceling stops future
                renewals; the current period remains active until it ends.
              </li>
              <li>
                Any unused portion of a free trial is forfeited when you purchase a paid
                subscription.
              </li>
            </ul>
          </Section>

          <Section title="4. Refunds">
            <p>
              All sales are processed by Apple. Refund requests are handled by Apple under
              its standard refund policy. Please submit refund requests through{" "}
              <a
                href="https://reportaproblem.apple.com"
                target="_blank"
                rel="noopener noreferrer"
                className="text-[#00B5A3] hover:underline"
              >
                reportaproblem.apple.com
              </a>
              .
            </p>
          </Section>

          <Section title="5. Health Information; Not Medical Advice">
            <p>
              The App helps you export and organize health and fitness data you already
              collect through Apple Health and connected devices. The App is not a medical
              device. Reports generated by the App are for your personal informational use
              and for sharing at your discretion. The App does not provide medical advice,
              diagnosis, or treatment. Always consult a qualified healthcare professional
              about any medical concern. Never disregard or delay seeking professional
              medical advice because of something you read in a report generated by the App.
            </p>
          </Section>

          <Section title="6. Your Data and Storage">
            <p>
              The App reads health data on your device and writes generated reports to cloud
              storage you own and authorize (for example, your Google Drive). HealthShare
              does not operate a server that retains your health data. Your relationship
              with your storage provider is governed by that provider&rsquo;s terms.
            </p>
          </Section>

          <Section title="7. Acceptable Use">
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 mt-4 space-y-2">
              <li>Reverse engineer, decompile, or attempt to extract the source code of the App, except where permitted by law.</li>
              <li>Use the App to violate any law or third-party right.</li>
              <li>Use the App to process health data of any person who has not authorized you to do so.</li>
              <li>Interfere with or disrupt the integrity or performance of the App.</li>
            </ul>
          </Section>

          <Section title="8. Disclaimer of Warranties">
            <p>
              The App is provided &ldquo;AS IS&rdquo; and &ldquo;AS AVAILABLE&rdquo; without
              warranty of any kind, whether express, implied, or statutory, including
              warranties of merchantability, fitness for a particular purpose, accuracy, or
              non-infringement. We do not warrant that the App will be uninterrupted,
              error-free, or that any defects will be corrected.
            </p>
          </Section>

          <Section title="9. Limitation of Liability">
            <p>
              To the maximum extent permitted by law, in no event will HealthShare or its
              suppliers be liable for any indirect, incidental, special, consequential, or
              punitive damages, or any loss of profits, revenue, data, or use, arising out
              of or relating to your use of the App. Our aggregate liability for any claim
              relating to the App will not exceed the amount you paid to use the App in the
              twelve months preceding the claim, or, if greater, USD $50.
            </p>
          </Section>

          <Section title="10. Termination">
            <p>
              We may suspend or terminate your access to the App at any time if you breach
              these Terms. You may stop using the App at any time by uninstalling it and
              canceling any active subscription through your Apple ID settings.
            </p>
          </Section>

          <Section title="11. Changes">
            <p>
              We may update these Terms from time to time. If changes are material, we will
              provide reasonable notice through the App or by updating the effective date
              above. Continued use of the App after the effective date constitutes
              acceptance of the updated Terms.
            </p>
          </Section>

          <Section title="12. Apple-Specific Terms">
            <p>
              You and HealthShare acknowledge that these Terms are between you and
              HealthShare only, not with Apple, and that Apple is not responsible for the
              App or its content. Apple has no obligation to provide maintenance or support
              for the App. In the event the App fails to conform to any applicable warranty,
              you may notify Apple and Apple will refund the purchase price, if any, for the
              App; to the maximum extent permitted by law, Apple has no other warranty
              obligation with respect to the App. Apple and its subsidiaries are
              third-party beneficiaries of these Terms and have the right to enforce them
              against you.
            </p>
          </Section>

          <Section title="13. Contact">
            <p>
              For questions about these Terms, contact us at{" "}
              <a
                href="mailto:alexander.kaigorodow@gmail.com"
                className="text-[#00B5A3] hover:underline"
              >
                alexander.kaigorodow@gmail.com
              </a>
              .
            </p>
          </Section>
        </article>
      </main>
      <Footer />
    </>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">{title}</h2>
      <div className="space-y-3">{children}</div>
    </section>
  );
}
